@echo off
echo HelperBatchFiles\AnacondeInstaller_DownloadAndRun.bat
echo HelperBatchFiles\InstallExternalPackages.bat
echo HelperBatchFiles\GetTensorFlow.bat
echo HelperBatchFiles\InstallKeras.bat
echo HelperBatchFiles\Git_Install.bat