@echo off
HelperBatchFiles\AnacondeInstaller_DownloadAndRun.bat
HelperBatchFiles\InstallExternalPackages.bat
HelperBatchFiles\GetTensorFlow.bat
HelperBatchFiles\InstallKeras.bat
HelperBatchFiles\Git_Install.bat